import os
DEBUG=True
SECRET_KEY=os.urandom(24)#设置session的加密方式
HOSTNAME='127.0.0.1'
PORT='3306'
DATABASE='student' 
USERNAME='root'
PASSWORD='123456'
DB_URL='mysql+pymysql://{}:{}@{}:{}/{}?charset=utf8'.format(USERNAME,PASSWORD,HOSTNAME,PORT,DATABASE)
SQLALCHEMY_DATABASE_URI=DB_URL#按照这个格式写
SQLALCHEMY_TRACK_MODIFICATIONS=True
